#!/usr/bin/env perl
use 5.036;
use strict;
use warnings;

use Cwd qw(abs_path);
use File::Basename qw(dirname);
use File::Spec;
use Getopt::Long qw(GetOptions);
use POSIX qw(strftime);

my $save  = 0;
my $print = 0;
my $help  = 0;

GetOptions(
    'save'  => \$save,
    'print' => \$print,
    'help'  => \$help,
) or usage(2);

usage(0) if $help;

my $script_dir = abs_path(dirname(__FILE__)) or die "Could not locate the script\n";
my $repo_root  = abs_path(File::Spec->catdir($script_dir, File::Spec->updir))
    or die "Could not locate the repository\n";
my $output = File::Spec->catfile($repo_root, 'hardware', 'inxi-Fz.txt');

open my $pipe, '-|', 'inxi', '-Fz', '--color', '0'
    or die "Could not run inxi: $!\n";
local $/;
my $report = <$pipe> // '';
close $pipe or die "inxi exited with an error\n";

if ($print || !$save) {
    print $report;
    exit 0;
}
open my $file, '>', $output or die "Could not write $output: $!\n";
print {$file} '# Snapshot generated by `inxi -Fz` on '
    . strftime('%Y-%m-%d %H:%M:%S %z', localtime) . "\n\n";
print {$file} $report;
close $file or die "Could not close $output: $!\n";
say "Snapshot saved to $output";

sub usage {
    my ($status) = @_;
    print <<'USAGE';
Usage: perl scripts/hardware-profile.pl [options]

  --save    updates hardware/inxi-Fz.txt
  --print   prints the report (default behavior)
  --help    shows this help
USAGE
    exit $status;
}
