-- Liquid Glass for Omarchy: glass on terminals + the window look.
-- GENERATED by Glass Tuner (Super+Ctrl+G, Save). Edit with the tuner, not by hand:
-- values live in ~/.config/omarchy-liquid-glass/state.json.
-- https://github.com/fasi96/omarchy-liquid-glass
if hl.plugin.hyprglass then
  hl.plugin.hyprglass.config({ enabled = false, default_theme = "dark", default_preset = "default",
    blur_strength = 0.5, blur_iterations = 1, refraction_strength = 3.0, chromatic_aberration = 1.0, lens_distortion = 3.0, edge_thickness = 0.07, fresnel_strength = 2.0, specular_strength = 3.0, glass_opacity = 1.0, tint_color = 0x8899aa33,
    dark = { brightness = 1.0, contrast = 0.9, saturation = 1.6, vibrancy = 0.81, vibrancy_darkness = 0.14, adaptive_dim = 0.3, adaptive_boost = 0.02 } })
  -- Liquid Glass motion (HyprGlass Liquid fork)
  hl.plugin.hyprglass.config({ light_strength = 1.5, light_x = 0.25, light_y = -0.35, light_sharpness = 4.0, light_width = 20.0, light_far = 0.35, light_bend = 1.2, light_cursor = 0.6, light_inactive = 0.6, light_drift = 0.0, light_drift_period = 45.0, light_lag = 0.25, parallax_strength = 37.2, parallax_depth = 3.0, oil_amount = 0.352, oil_speed = 0.802, oil_scale = 220.0, oil_color = 1.0, oil_warp = 4.0, oil_inactive = 1.0, oil_fps = 30.0, glow_strength = 0.0, glow_duration = 0.8, glow_spread = 0.312, glow_ring = 73.0, glow_flex = 1.72, materialize_duration = 1.044, light_color = 0xffffff })
end

hl.config({
  general = { gaps_in = 8, gaps_out = 16, border_size = 1,
    col = { active_border = { colors = { "rgba(22d3eeff)", "rgba(8b5cf6ff)", "rgba(ec4899ff)" }, angle = 45 }, inactive_border = "rgba(ffffff18)" } },
  decoration = { rounding = 12, shadow = { enabled = true } },
})
hl.animation({ leaf = "borderangle", enabled = true, speed = 60, bezier = "linear", style = "loop" })

o.window({ tag = "terminal" }, { tag = "+hyprglass_enabled" })
