# Ajustes enxutos para i5-1135G7, 16 GiB e Iris Xe.
color_theme = "current"
theme_background = true
truecolor = true
graph_symbol = "braille"
shown_boxes = "cpu mem net proc"
update_ms = 2000
proc_sorting = "cpu lazy"
proc_per_core = false
proc_mem_bytes = true
show_uptime = true
check_temp = true
show_cpu_freq = true
show_swap = true
swap_disk = true
